# Generated by Django 6.1 on 2026-09-11 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0004_resume_alter_certification_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Training',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('program_name', models.CharField(default='Full Stack Development – Python', max_length=200)),
                ('institution', models.CharField(default='Mastermind Techno Solution', max_length=200)),
                ('duration', models.CharField(default='Nov 2024 – Jul 2025', max_length=100)),
                ('topics', models.CharField(default='Python, Django, Web Development, Database, Full Stack Development', max_length=300)),
                ('description', models.TextField(blank=True, default='')),
                ('certificate_link', models.URLField(blank=True)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Training Program',
                'verbose_name_plural': 'Training Programs',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.AlterModelOptions(
            name='contactmessage',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='education',
            options={'verbose_name_plural': 'Education'},
        ),
        migrations.AlterModelOptions(
            name='experience',
            options={'ordering': ['-id']},
        ),
        migrations.AlterModelOptions(
            name='project',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='skill',
            options={'ordering': ['category', 'order', 'name']},
        ),
        migrations.AddField(
            model_name='education',
            name='university',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='experience',
            name='is_current',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='experience',
            name='location',
            field=models.CharField(blank=True, default='Chennai, Tamil Nadu', max_length=150),
        ),
        migrations.AddField(
            model_name='project',
            name='detailed_description',
            field=models.TextField(blank=True, default='', help_text='In-depth project breakdown, problem statement, and solution'),
        ),
        migrations.AddField(
            model_name='project',
            name='features',
            field=models.TextField(blank=True, default='', help_text='Key features (one per line or comma-separated)'),
        ),
        migrations.AddField(
            model_name='skill',
            name='category',
            field=models.CharField(choices=[('BACKEND', 'Backend Development'), ('DATABASE', 'Database'), ('FRONTEND', 'Frontend Development'), ('TOOLS', 'Tools & Workflow'), ('OTHER', 'Other Technical Skills')], default='BACKEND', max_length=20),
        ),
        migrations.AddField(
            model_name='skill',
            name='order',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='education',
            name='percentage',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='experience',
            name='description',
            field=models.TextField(help_text='Role summary or bullet points separated by newlines'),
        ),
        migrations.AlterField(
            model_name='project',
            name='description',
            field=models.TextField(help_text='Short overview of the project'),
        ),
        migrations.AlterField(
            model_name='project',
            name='github_link',
            field=models.URLField(blank=True, help_text='Repository URL'),
        ),
        migrations.AlterField(
            model_name='project',
            name='image',
            field=models.ImageField(blank=True, help_text='Project preview or architecture screenshot', null=True, upload_to='projects/'),
        ),
        migrations.AlterField(
            model_name='project',
            name='live_link',
            field=models.URLField(blank=True, help_text='Live deployment URL (leave empty if not deployed)'),
        ),
        migrations.AlterField(
            model_name='project',
            name='technologies',
            field=models.CharField(help_text='Comma-separated list of technologies used (e.g. Python, Django, MySQL)', max_length=300),
        ),
        migrations.AlterField(
            model_name='skill',
            name='percentage',
            field=models.IntegerField(default=85, help_text='Internal proficiency indicator'),
        ),
    ]
